version: '2'

services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "13306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "golab"
      MYSQL_DATABASE: golab
      MYSQL_USER: golab
      MYSQL_PASSWORD: golab